<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <OutputType>Library</OutputType>
    <GenerateAssemblyInfo>false</GenerateAssemblyInfo>
    <EmbedUntrackedSources>true</EmbedUntrackedSources>
    <IncludeSymbols>true</IncludeSymbols>
    <IncludeSource>true</IncludeSource>
    <Deterministic>true</Deterministic>
    <Optimize>true</Optimize>
  </PropertyGroup>
  <ItemGroup>
    <Compile Include="..\CommonAssemblyInfo.cs">
      <Link>Properties\CommonAssemblyInfo.cs</Link>
    </Compile>
  </ItemGroup>
  <ItemGroup>
    <None Include="..\LICENSE.txt">
      <Pack>True</Pack>
      <PackagePath>\</PackagePath>
    </None>
    <None Include="..\NINA\Resources\ninasplash.png">
      <Pack>True</Pack>
      <PackagePath>\</PackagePath>
    </None>
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\NINA.Astrometry\NINA.Astrometry.csproj" />
    <ProjectReference Include="..\NINA.Core\NINA.Core.csproj" />
    <ProjectReference Include="..\NINA.Equipment\NINA.Equipment.csproj" />
    <ProjectReference Include="..\NINA.Image\NINA.Image.csproj" />
    <ProjectReference Include="..\NINA.Profile\NINA.Profile.csproj" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="System.Data.SqlClient" Version="4.9.0" />
  </ItemGroup>
  <PropertyGroup>
    <Description>This assembly contains the Platesolving components of N.I.N.A. to invoke different platesolvers.</Description>
    <Title>$(AssemblyName)</Title>
    <Version>3.3.0.1048-nightly</Version>
    <Authors>Stefan Berg and the N.I.N.A. Contributors</Authors>
    <Product>N.I.N.A. - Nighttime Imaging 'N' Astronomy</Product>
    <Copyright>Copyright ©  2016 - 2026 Stefan Berg and the N.I.N.A. contributors</Copyright>
    <PackageProjectUrl>https://nighttime-imaging.eu/</PackageProjectUrl>
    <PackageIcon>ninasplash.png</PackageIcon>
    <RepositoryUrl>https://github.com/isbeorn/nina.git</RepositoryUrl>
    <PackageOutputPath>$(SolutionDir)publish</PackageOutputPath>
    <GeneratePackageOnBuild>True</GeneratePackageOnBuild>
    <PackageLicenseFile>LICENSE.txt</PackageLicenseFile>
  </PropertyGroup>
</Project>
